call plug#begin('~/.vim/plugged')

" Color scheme
Plug 'KeitaNakamura/neodark.vim'
Plug 'itchyny/lightline.vim'

call plug#end()

set backspace   =indent,eol,start  " Make backspace work as you would expect.

set cursorline             " Find the current line quickly.

set number                     " Show current line number
set relativenumber             " Show relative line numbers

set noshowmode
set noshowcmd

set laststatus=2

let &t_Co=256 " Explicit 256 color support

colorscheme neodark
